# Generated by Django 2.2.2 on 2019-07-05 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(blank=True, to='flapp.Tag'),
        ),
    ]
