# Generated by Django 2.2.2 on 2019-06-22 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='editor',
            old_name='desination',
            new_name='designation',
        ),
    ]
