# Generated by Django 2.2.2 on 2019-07-06 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flapp', '0002_auto_20190705_2251'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
