# Generated by Django 2.2.2 on 2019-07-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flapp', '0003_delete_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writer',
            name='designation',
            field=models.CharField(choices=[('A', 'Author'), ('GA', 'Guest Author'), ('FO', 'Founder')], default='A', max_length=2),
        ),
        migrations.DeleteModel(
            name='Founder',
        ),
    ]
